#!/usr/bin/bash

MEMORY_LIMIT=1500
EXP=PageRank_big
if [ $# -eq 2 ]; then
	MEMORY_LIMIT=$1
	EXP=$2
	echo "memory limit ${MEMORY_LIMIT} and ${EXP}"
else
	echo "memory limit ${MEMORY_LIMIT} and ${EXP}"
fi

sudo systemd-run --scope -p MemoryLimit=${MEMORY_LIMIT}M -p AllowedCPUs=21,22,23,24,25,36,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46 /home/legrain/jdk11u/build/linux-x86_64-normal-server-release/jdk/bin/java \
	-XX:AllocateHeapAt=/dev/astenn -Xlog:gc=debug \
	-XX:-OptimizeStringConcat \
	-XX:+UnlockExperimentalVMOptions \
	-XX:+UseEpsilonGC -Xnoclassgc \
	-XX:+AlwaysPreTouch \
	-XX:-ClassUnloading \
	-XX:TieredStopAtLevel=1 \
       	-Xms24g \
	-Xmx24g \
	-XX:+UseCompressedOops \
	-Djboss.socket.binding.port-offset=100 -classpath "/home/legrain/Spark_benchmark/spark_blk/conf/:/home/legrain/Spark_benchmark/spark_blk/jars/*"  org.apache.spark.deploy.SparkSubmit \
      	--conf "spark.driver.extraJavaOptions=-Dlog4j.rootCategory=WARN,console" \
	--conf "spark.executor.extraJavaOptions=-Dlog4j.rootCategory=WARN,console"\
	--master local[*] --class "${EXP}" /home/legrain/Spark_benchmark/spark_run/run.jar 


#sudo systemd-run --scope -p MemoryLimit=${MEMORY_LIMIT}M -p AllowedCPUs=21,22,23,24,25,36,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46 /home/legrain/jdk11u/build/linux-x86_64-normal-server-release/jdk/bin/java \
#	-XX:AllocateHeapAt=/dev/astenn -Xlog:gc=debug \
#	-XX:-OptimizeStringConcat \
#	-XX:+UnlockExperimentalVMOptions \
#	-XX:+UseEpsilonGC -Xnoclassgc \
#	-XX:+AlwaysPreTouch \
#	-XX:-ClassUnloading \
#	-XX:TieredStopAtLevel=1 \
#       	-Xms24g \
#	-Xmx24g \
#	-Djboss.socket.binding.port-offset=100 -classpath "/home/legrain/Spark_benchmark/spark_blk/conf/:/home/legrain/Spark_benchmark/spark_blk/jars/*"  org.apache.spark.deploy.SparkSubmit   --master local[*] --class TransitiveClosure /home/legrain/Spark_benchmark/spark_run/run.jar --input /home/legrain/twitter_combined.txt --output /tmp/closure.parquet
#
